"use client";

import './global.css';
import { UiLayout } from '@/components/ui/ui-layout';
import { ClusterProvider } from '@/components/cluster/cluster-data-access';
import { SolanaProvider } from '@/components/solana/solana-provider';
import { ReactQueryProvider } from './react-query-provider';
import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react';
import { WalletModalProvider } from '@solana/wallet-adapter-react-ui';
import { clusterApiUrl } from '@solana/web3.js';
import Navbar from '@/components/Navbar';
import "@solana/wallet-adapter-react-ui/styles.css";

// export const metadata = {
//   title: 'dapp0',
//   description: 'Generated by create-solana-dapp',
// };

const links: { label: string; path: string }[] = [
  { label: 'Account', path: '/account' },
  { label: 'Clusters', path: '/clusters' },
  { label: 'Dapp0 Program', path: '/dapp0' },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const endpoint=clusterApiUrl("devnet");
  return (
    <html lang="en">
      <body>
        {/* <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <UiLayout links={links}>{children}</UiLayout>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider> */}
        <ConnectionProvider endpoint={endpoint}>
          <WalletProvider wallets={[]}>
            <WalletModalProvider>
              <Navbar/>
              {children}
            </WalletModalProvider>
          </WalletProvider>
        </ConnectionProvider>
      </body>
    </html>
  );
}
